Fix a problem where the latest version could not be obtained

diff --git a/libexec/ghr-get-latest-version b/libexec/ghr-get-latest-version
--- a/libexec/ghr-get-latest-version
+++ b/libexec/ghr-get-latest-version
@@ -8,11 +8,9 @@ if [ -z "$package" ]; then
   exit 1
 fi
 
-url=https://github.com/$package/releases/latest
-html=$(curl -fsSL $url) || abort "Package '$package' is not found"
+url="$(eval echo $LATEST_PAGE_URL)"
+headers=$(curl -IfsS $url) || abort "Package '$package' is not found"
 
-echo "$html" |
-  grep -o "/$package/releases/download/[^\"]*" |
-  awk -F/ '{print $6}' |
-  sort |
-  uniq
+echo "$headers" |
+  grep '^location: ' |
+  awk -F/ '{print $8}'
